primeraEntrega_FontaoAlejo/VentasNet/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using QuestPDF.Fluent;
﻿using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VentasNet.Infra.Repository.Interfaz;
using VentasNet.Entity.Models;
using VentasNet.Infra.DTO.Request;

namespace TrabajoPractico1.Controllers
{
    public class ClienteController : Controller
    {
       
        private readonly IWebHostEnvironment _host;
        private readonly IClienteRepository _clienteRepository;

		public ClienteController(IClienteRepository clienteRepository, IWebHostEnvironment host)
        {
            _clienteRepository = clienteRepository;
			_host = host;
        }
        
        public IActionResult ListaClientes()
        {
			ViewBag.Cliente = _clienteRepository.ObtenerTodos();
			return View();
		}

        [HttpPost]
        public IActionResult AgregarCliente(ClienteRequest cliente)
        {
			var result = _clienteRepository.Agregar(cliente);
			return RedirectToAction("ListaClientes");
		}

        [HttpPost]
        public IActionResult ModificarCliente(ClienteRequest cliente)
        {
            _clienteRepository.Modificar(cliente);
            return RedirectToAction("ListaClientes");
        }

        [HttpPost]
        public IActionResult EliminarCliente(ClienteRequest clienteAEliminar)
        {
      
            if (clienteAEliminar != null)
            {
                _clienteRepository.Eliminar(clienteAEliminar);
            }

            return RedirectToAction("ListaClientes");
        }

        [HttpGet]
        public List<Cliente> ObtenerClienteByDato(ClienteBusquedaRequest clienteBusquedaRequest)
        {
            var clientes = _clienteRepository.ObtenerClienteByDato(clienteBusquedaRequest);
            return clientes;
        }
    }
}

primeraEntrega_FontaoAlejo/VentasNet/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using VentasNet.Infra.DTO.Request;
using VentasNet.Infra.Repository.Interfaz;

namespace TrabajoPractico1.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoRepository _productoRepository;

        public ProductoController(IProductoRepository productoRepository)
        {
            _productoRepository = productoRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListaProducto()
        {
            ViewBag.Producto = _productoRepository.ObtenerTodos();
            return View();
        }

        [HttpPost]
        public IActionResult AgregarProducto(ProductoRequest producto)
        {
            _productoRepository.Agregar(producto);
            return RedirectToAction("ListaProducto");
        }

        [HttpPost]
        public IActionResult ModificarProducto(ProductoRequest producto)
        {
            _productoRepository.Modificar(producto);
            return RedirectToAction("ListaProducto");
        }

        [HttpPost]
        public IActionResult EliminarProducto(ProductoRequest productoAEliminar)
        {
            
            if (productoAEliminar != null)
            {
                _productoRepository.Eliminar(productoAEliminar);
            }

            return RedirectToAction("ListaProducto");
        }
    }
}

primeraEntrega_FontaoAlejo/VentasNet/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using VentasNet.Entity.Models;
using VentasNet.Infra.DTO.Request;
using VentasNet.Infra.Repository;
using VentasNet.Infra.Repository.Interfaz;

namespace TrabajoPractico1.Controllers
{
    public class UsuarioController : Controller
    {
        private IUsuarioRepository _usuarioRepository;
        public UsuarioController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult ListaUsuario()
        {
            ViewBag.Usuario = _usuarioRepository.ObtenerTodos();
            return View();
        }

        [HttpPost]
        public IActionResult AgregarUsuario(UsuarioRequest usuario)
        {
            _usuarioRepository.Agregar(usuario);
            return RedirectToAction("ListaUsuario");
        }

        [HttpPost]
        public IActionResult ModificarUsuario(int IdUsuario, string contraseniaAntigua, UsuarioRequest usuario)
        {
            var usuarioPass = _usuarioRepository.ObtenerById(IdUsuario).Password;
            if (usuarioPass == contraseniaAntigua)
            {
                _usuarioRepository.Modificar(usuario);
                return RedirectToAction("ListaUsuario");
            }
            else
            {
                TempData["Error"] = "Contraseña incorrecta";
                return RedirectToAction("ListaUsuario");
            }
        }

        [HttpPost]
        public IActionResult EliminarUsuario(UsuarioRequest usuarioAEliminar)
        {
          
            if (usuarioAEliminar != null)
            {
                _usuarioRepository.Eliminar(usuarioAEliminar);
            }

            return RedirectToAction("ListaUsuario");
        }
    }
}

primeraEntrega_FontaoAlejo/VentasNet/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Security;
using VentasNet.Entity.Models;
using VentasNet.Infra.DTO.Request;
using VentasNet.Infra.DTO.Response;
using VentasNet.Infra.Repository;
using VentasNet.Infra.Repository.Interfaz;

namespace VentasNet.Controllers
{
    public class VentaController : Controller
    {
        private List<Producto> _carrito = new List<Producto>();
        private IEnumerable<ProductoRequest> _productos = new List<ProductoRequest>();
        private readonly IProductoRepository _productoRepository;
        private readonly IVentaRepository _ventaRepository;
        private readonly IFormaDePagoRepository _formaDePagoRepository;
        public VentaController(IProductoRepository productoRepository, IVentaRepository ventaRepository, IFormaDePagoRepository formaDePagoRepository)
        {
            _productoRepository = productoRepository;
            _ventaRepository = ventaRepository;
            _formaDePagoRepository = formaDePagoRepository;
        }
        public IActionResult Venta()
        {

            return View();
        }

        public IActionResult ListaProducto()
        {
            _productos = _productoRepository.ObtenerTodos();
            ViewBag.FormasDePago = _formaDePagoRepository.ObtenerTodos();
            ViewBag.Producto = _productos;
            return View();
        }

        public IEnumerable<ProductoRequest> BuscarPorNombre(string nombre)
        {
            return _productoRepository.ObtenerPorNombreLista(nombre);
        }

        [HttpPost]
        public IActionResult GenerarVenta([FromBody] List<ItemRequest> elementosCarrito)
        {
            Response response = _ventaRepository.AgregarVenta(elementosCarrito);
            if (response.Guardar)
            {
                return Ok(response.TextMensaje);
            }
            else
            {
                return BadRequest(response.TextMensaje);
            }
        }
    }
}

primeraEntrega_FontaoAlejo/VentasNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrabajoPractico3</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrabajoPractico3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="ListaClientes">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="ListaProveedor">Proveedores</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ListaProducto">Venta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="ListaProducto">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="ListaUsuario">Usuario</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TrabajoPractico2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div
       
    </footer>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>